redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\SAM\\OneDrive\\Desktop\\TREASURY DIRECT\\treasurydirect-mirror"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/RS/UN-Display.do"
to = "/log-in/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/RS/UN-Submit.do"
to = "/dashboard/"
status = 303.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/RS/UN-AccountCreate.do"
to = "/open-account/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/dashboard"
to = "/dashboard/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/log-in"
to = "/log-in/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/open-account"
to = "/open-account/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]